基本機能を実装
m0use-dev/todoapp pull request #2
Opened 2023-12-17 06:19 UTC by m0use-dev

2023-12-17 15:50 UTC, codestep-ito requested changes
まだ動かしていないのですが、全般的に独力でよく作られているように感じました。
特に画面系に関しては目視でコードを見る限りでは問題はなさそうに思います。
Java側のコードについても大きくおかしいところは見受けられませんでした。

より細かく、動作させながら見ていきたいと思いますが
複数のファイルが一気にコミットされていることもあり、レビューがしづらいところがありました。

業務で実施することを想定し、レビューをするにあたっては下記のポイントに注意してレビューを依頼してみてください

- このアプリがどういう構成でどういう動作をするのか
- レビューをしてほしい場所はどこか（どういう観点で確認してほしいか）
- 動作の確認が必要であればその方法
- data.sqlを作成しているのはとても良いと思いますが、これがどのように使われるのか

また、下記の項目に注意しましょう

- 不要なコードを残さないこと
- 必要な箇所にコメントを記載すること（今回このコメントもなかったことが全体の機能として何がどう呼ばれるかを判断するのが難しくなってしまいました）

その他

- カリキュラムに関する変更点についてお知らせしていなかったぶん、より複雑なものを作成していただいてしまいました。ユーザに関しては今回IDを利用しない、という方針でSpringSecurityを利用していただく、という方法でお願いいたします。

以上を踏まえて修正をお願いします。

2023-12-17 15:50 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        int userId = userService.getUserId(username);
この部分ですが、大変申し訳ありませんが、カリキュラムの変更がありました。
データベースのテーブル定義の変更の必要がありまして、
usersテーブルにidを持たない方針としていただきたく思います。（合わせてusernameがuniqueになります）

結果として、保持してほしいのは「ID」ではなく「username」とする仕様としていただけますでしょうか。
（結果的に他のテーブルへの仕様変更が必要となってしまうと思います）

関連しそうな変更が必要な箇所を合わせてご対応いただけますか。

2023-12-17 15:50 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        var postList = postService.getPosts(userId)
ここで「var」を用いている理由にはどのようなことがありますか？

2023-12-17 15:50 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        model.addAttribute("lastWeek", LocalDate.now().minusDays(7));
ここで「７」という数字を直接埋め込んでいることはあまり望ましくありません。
この部分を関数として別に切り出すことは可能でしょうか？
（切り出した関数の中で７を使うことはOKとします）

2023-12-17 15:50 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        model.addAttribute("lastWeek", LocalDate.now().minusDays(7));
またこちらは調べたかどうかの確認ですが、LocalDate.now()  を同じプログラム内で複数回実行した時、その値は必ず同じになりますか？（日付をまたぐ瞬間にこの行と次の行が実行されても問題ないですか？）

2023-12-17 15:50 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostDTO.java
> +//        @NotNull
ここでコメントアウトが利用されている理由はなにかありますか？

2023-12-17 15:50 UTC, codestep-ito commented on README.md
> +| password | TINYINT | NO |  |
passwordではなく、enabledがTINYINTだと思います。

2024-01-14 08:13 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        model.addAttribute("lastWeek", LocalDate.now().minusDays(7));
> 日付をまたぐ瞬間にこの行と次の行が実行されても問題ないですか？
この場合は、別々の日付が代入される認識で使用していました。

LocalDateTでの検証方法が分からなかったため、機能が似ているLocalDateTimeを使用した場合は、下記のように別々の時間が代入されました。
2024-01-14T16:56:45.271124
2024-01-14T16:56:45.271136

2024-01-14 08:28 UTC, m0use-dev commented on README.md
> +| password | TINYINT | NO |  |
一つずれて入力していました。申し訳ございません。

2024-01-14 08:39 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        var postList = postService.getPosts(userId)
参考にした教材がvarで書かれていたので、「var」を使用しました。

教材でvarを使用する理由について書かれていなかったので、複数の型が読み込まれているときに使う認識で作業を進めました。

2024-01-14 08:43 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostDTO.java
> +//        @NotNull
@NotNullがあった方が良いのか、わからず
後々に調べるためにコメントアウトにしていました。

2024-01-15 12:51 UTC, codestep-ito commented on README.md
> +| password | TINYINT | NO |  |
特に謝る必要はないです！ただの指摘なので！
修正しておきましょう。

2024-01-15 12:52 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostDTO.java
> +//        @NotNull
最終的に提出などするコードからはコメントアウト（意味のない内容を残すこと）は避けたほうがいいです。
コードに対して意味があるコメントを残しておくのは意味があるのですが、
必要かどうかわからないからとりあえず、というのは望ましくないです。

※ こういう「どうしたらよいか迷っています」についてもレビューとしては意味があるので、そこで聞くのが良いです。

2024-01-15 12:54 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        model.addAttribute("lastWeek", LocalDate.now().minusDays(7));
まず「問題ないか」について答えるようにしましょう。
「認識で使用してしました」だとどちらか曖昧なので。

この場合の指摘は日が変わるタイミングで実行したときに
1/13と1/14のように表示される日付がずれてしまう可能性がありうることを気にしています。
場合によってはこれが不具合になる（そして、この機能上はこれは不具合に私には見える）ので
意図的にやったのであればそれでも問題ないという考えについて触れてもらうと良いと思います。

2024-01-15 12:56 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        var postList = postService.getPosts(userId)
なるほど、別の書籍だったんですね。
Java10から利用可能な構文にはなっていますが、せっかくの型を明示するというJavaのメリットを活かしていないという考え方もあったりはするので、もし可能であれば使わないプログラミングを心がけると良いと思います。（使うなといっているわけではありませんし、ここを修正する必要もありません）

2024-02-14 14:03 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        int userId = userService.getUserId(username);
関連箇所の修正を行いコミットを行いました。

2024-02-14 14:09 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        model.addAttribute("lastWeek", LocalDate.now().minusDays(7));
関数の利用と日付ずれるバグ対応を行いましたが、
下記のコードで大丈夫でしょうか。

```java:
public LocalDate getLastDate(LocalDate today) {
  return today.minusDays(7);
}
```

```java
LocalDate today = LocalDate.now();
model.addAttribute("today", today);
LocalDate lastWeek = postService.getLastDate(today);
model.addAttribute("lastWeek", lastWeek);
```

2024-02-15 02:36 UTC, codestep-ito commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        model.addAttribute("lastWeek", LocalDate.now().minusDays(7));
はい。このように、LocalDate.now() したものを変数に入れることで問題は起こらなくなりますね！

getLastDateという命名が良いかというのは検討の余地はありますが、これで良いと思います。

「7」という数字がそのまま入っていることは「マジックナンバー」と言われる問題を抱えているように思いますが「一週間は7日」は変わることがないので、問題ないと言えると思います。

2024-02-15 14:15 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostDTO.java
> +//        @NotNull
// @NotNull
のバリデーション箇所は、コメント解除か削除で悩みましたが
データの読み込みだけの処理でバリデーションが必要ないを考え削除いたしました。

こちらのファイルのバリデーションも同様の内容で削除いたしました。
src/main/java/com/example/todoapp/controller/user/UserDTO.java

こちらのファイルは、タスクの追加と処理にバリデーションを使用しているので、残したままにしています。
src/main/java/com/example/todoapp/controller/post/PostForm.java

2024-02-15 14:20 UTC, m0use-dev commented on README.md
> +| password | TINYINT | NO |  |
READMEの修正を行いました。

2024-02-15 14:25 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        var postList = postService.getPosts(userId)
かしこまりました。
次回から、宣言する型を意識して宣言いたします。

2024-02-17 04:31 UTC, m0use-dev commented on src/main/java/com/example/todoapp/controller/post/PostController.java
> +        model.addAttribute("lastWeek", LocalDate.now().minusDays(7));
ご確認ありがとうございます。

関数名ですが、間違えて命名していたため、こちらに変更いたしました。
「getLastDate」→「getLastWeek」

2024-02-17 15:00 UTC, codestep-ito commented
内容すべて確認いたしました。ここまで問題ありません。このまま進めてください。

2024-02-17 15:14 UTC, merged